In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

In [ ]:
mail_data=pd.read_csv('/content/mail_data.csv')

In [ ]:
print(mail_data)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [ ]:
mail_data=mail_data.where((pd.notnull(mail_data)),'')
mail_data.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
mail_data.shape

(5572, 2)

Label encoding

In [ ]:
#spam mail-0
#ham mail-1
mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0
mail_data.loc[mail_data['Category'] == 'ham', 'Category'] = 1

In [ ]:
#separating the data as texts and labels
x=mail_data['Message']
y=mail_data['Category']

In [ ]:
print(x)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
print(y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [ ]:
print(x.shape)
print(x_train.shape)
print(x_test.shape)

(5572,)
(4457,)
(1115,)

feature extraction

In [ ]:
feature_extraction=TfidfVectorizer(min_df=2,stop_words='english',lowercase=True)

In [ ]:
x_train_features=feature_extraction.fit_transform(x_train)
x_test_features=feature_extraction.transform(x_test)

In [ ]:
#convert y_train and y_test values as integer
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [ ]:
print(x_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30754 stored elements and shape (4457, 3410)>
  Coords	Values
  (0, 1023)	0.38783870336935383
  (0, 1700)	0.34780165336891333
  (0, 975)	0.413103377943378
  (0, 2039)	0.4168658090846482
  (0, 2456)	0.6198254967574347
  (1, 1700)	0.17419952275504033
  (1, 1358)	0.2503712792613518
  (1, 879)	0.33036995955537024
  (1, 1315)	0.33036995955537024
  (1, 1229)	0.3226407885943799
  (1, 805)	0.2784903590561455
  (1, 381)	0.22871581159877646
  (1, 1223)	0.3398297002864083
  (1, 1316)	0.3398297002864083
  (1, 1482)	0.31610586766078863
  (1, 1421)	0.29694482957694585
  (1, 1836)	0.18880584110891163
  (2, 1060)	0.5691502728674215
  (2, 1405)	0.5161745479043828
  (2, 144)	0.6400248456041734
  (3, 3408)	0.8100020912469564
  (3, 1274)	0.5864269879324768
  (4, 1274)	0.4590807519984635
  (4, 3240)	0.16102151234615197
  (4, 2099)	0.17227330138021774
  :	:
  (4454, 2106)	0.4638016974218746
  (4454, 2806)	0.6896130870811723
  (4455, 2039)	0.24920025316220423
  (4455, 1751)	0.31287563163368587
  (4455, 3153)	0.19636985317119715
  (4455, 2147)	0.30714144758811196
  (4455, 1724)	0.3108911491788658
  (4455, 3253)	0.30536590342067704
  (4455, 2781)	0.23103841516927642
  (4455, 3106)	0.29731757715898277
  (4455, 2566)	0.33545678464631296
  (4455, 1090)	0.35441545511837946
  (4455, 988)	0.37052851863170466
  (4456, 1274)	0.31523196273113385
  (4456, 2631)	0.16243064490100795
  (4456, 108)	0.2220077711654938
  (4456, 2869)	0.2752760476857975
  (4456, 2844)	0.17573831794959716
  (4456, 3270)	0.3677554681447669
  (4456, 3273)	0.24083218452280053
  (4456, 2754)	0.21034888000987115
  (4456, 2528)	0.4619395404299172
  (4456, 2870)	0.30133182431707617
  (4456, 249)	0.30133182431707617
  (4456, 51)	0.292943737785358

Traning the model

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x_train_features,y_train)

LogisticRegression()

In [ ]:
#evaluating the trained model
predict_train_data=model.predict(x_train_features)
accuracy_train_data = accuracy_score(y_train, predict_train_data)

In [ ]:
print('Accuracy on training data : ', accuracy_train_data)

Accuracy on training data :  0.973749158626879

In [ ]:
predict_test_data=model.predict(x_test_features)
accuracy_test_data = accuracy_score(y_test, predict_test_data)

In [ ]:
print('accuracy on testing data:',accuracy_test_data)

accuracy on testing data: 0.9704035874439462

In [ ]:
#predictive system
input_mail=['URGENT! You have won a 1 week FREE membership']
#convert text to feature vectors
convert_input_mail=feature_extraction.transform(input_mail)
prediction=model.predict(convert_input_mail)
print(prediction)
if (prediction[0]==1):
  print('Ham mail')
else:
  print('Spam mail')

[0]
Spam mail